database:
    driver: %DB_DRIVER%
    host: %DB_HOST%
    username: %DB_USER%
    password: %DB_PASSWORD%
    databasename: %DB_USER%
    port: %DB_PORT%

locale: de_DE

timezone: Europe/Berlin

strict_variables: true


